name: build

on:
  push:
    branches: [ main ]
  #pull_request:
  #    branches: [ '**' ]
  workflow_dispatch:

jobs:
  windows_amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
        id: go
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install Wails Dependencies
        run: choco install nsis
      - name: Wails Doctor
        run: wails doctor
      - name: BUILD
        run: wails build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-build
          path: ./build/bin

  linux_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
        id: go
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Update package list
        run: sudo apt-get update
      - name: Wails Doctor
        run: wails doctor
      - name: Install Wails Dependencies
        run: sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: BUILD
        run: wails build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-build
          path: ./build/bin

  macos_amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
        id: go
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Wails Doctor
        run: wails doctor
      - name: BUILD
        run: wails build
      - name: 'Tar files'
        run: tar -cvf ./builded.tar ./build/bin
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64-build
          path: ./builded.tar

  macos_arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
        id: go
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Wails Doctor
        run: wails doctor
      - name: BUILD
        run: wails build
      - name: 'Tar files'
        run: tar -cvf ./builded.tar ./build/bin
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: ./builded.tar
